### ISSUE TITLE
Filter by traffic direction/pattern

### ISSUE THREAD

**Issue by silvanbitterli** [els0r/goProbe#203] opened 2023-09-06 07:40 UTC
Allow filtering by traffic direction as part of the condition.  

Usage examples:
- only incoming traffic (no responses sent): ` -c "dir = in"`
- only outgoing traffic (no responses received): `-c "dir = out"`
- unidirectional traffic (one direction only): `-c "dir = uni"`
- bidirectional traffic (both directions only): `-c "dir = bi"`

Syntax:
`-c "dir = {in|out|uni|bi}`

Conceptual considerations:
- Post-processing layer (allows filtering after aggregation but before `-n`; allows more fine-grained filters such as `packet count > 5`)
- Extend parser so it understands keywords similarly to tcpdump (e.g. `-c "in and tcp"`)
- Plugin interface (filtering, but also enrichment as in DNS lookup or procera app ID)

**Comment by els0r** [comment] 2023-09-07 01:55
Thanks for the submission and welcome to the repo 🎉 .

I would suggest we start with a simple implementation for the post-processing and take on the post-processing layer in follow-up issues/PRs if this pans out.

I can imagine that the fact that we introduce filtering on `types.Counters` will already bring interesting changes/additions to the code base. Even though it’s part of the the condition, I’d stay away from the `Node` and provide a separate data structure instead.

**Comment by fako1024** [comment] 2023-09-09 10:41
Great idea, and I basically concur with @els0r's assessment. There is one thing though I'd like to point out: Before adding post-processing steps we should have a discussion about #63 (and how these issues tie together). The rationale is this: Right now we _know_ we're basically doing stuff twice (as in: create a list of all flows to be displayed / returned on map level, then basically convert it to a results / row structure in memory, and _then_ do sorting / filtering etc.), which of course doesn't matter for small / aggregate queries, but if you're running a huge query it does matter and basically doubles the memory requirements for a brief period in time.
I'm a bit worried that we'll be blocking ourselves from looking into doing the filtering / sorting _before_ filling the results once we setup an intricate plugin / post-processing system (that will probably right now act on the results).
There's also the question of raw queries (@els0r I just realized we forgot to create an issue for the outstanding tasks from https://github.com/els0r/goProbe/issues/75 , I'll take care of that), which may also have an impact on how post-processing is to be implemented (since it has to work for raw queries as well I suppose).

**Comment by els0r** [comment] 2023-09-10 02:46
Agree on the not duplicating stuff as in: filtering before the data is filled into the results structure.

Here's a funky idea: inside the query runner, we use an `Iterator()` to grab the next flow (Key/Val) out of the hashmap. Why not craft an iterator for exactly the case of filtering `Val`s? As in: we change the iterator that is used for the for loop when the condition is parsed and "compile" an iterator which will return only `Val`s which fit the Counters pattern.

Minimal change inside the query runner to maximum effect. All we need to do is initialize the final flow map with the Iterator to be used.

Catch my drift?

As for the post-processing after: I agree with discarding as much as possible before filling into the results structure. Yet rest my case that, once the results structure is built, it's open season: if you want to write a dumb plugin that queries 5 APIs per flow record: knock yourself out. But it won't affect the core processing loops that came before it.

Filtering on hashmaps, cosmetics on results.

**Comment by fako1024** [comment] 2023-09-10 14:16
> Why not craft an iterator for exactly the case of filtering `Val`s? As in: we change the iterator that is used for the for loop when the condition is parsed and "compile" an iterator which will return only `Val`s which fit the Counters pattern.

Interesting idea, like it! What's more: We might go even deeper / easier about that. Looping over the `hashmap` already _does_ use an explicit iterator (unlike the "normal" Go map), so I might just extend the existing low-level implementation (i.e. provide a `FilteringIterator` of some kind) to allow filtering the counters _inside_ the inner loop of the map iteration. That way, the final map (or any map for that matter, if ever required) would basically just use a different intrinsic iterator to achieve what you want without external fiddling (with the bonus that it would make it easier to implement the in-map sorting because everything happens in the map implementation, reducing the risk of introducing regressions / dependency lock-ups)...

And yes, after sorting / filtering is done, the user is free to do what they want with the results... :stuck_out_tongue: 

How about this: I'll have a look at #213 next week (to see if raw queries raise new dependencies / requirements for this issue) and then we take it from there to cover both scenarios?

**Comment by els0r** [comment] 2023-09-11 00:09
That's exactly the direction I'm thinking of.

What would be cool is if you could provide the low-level handling of the `FilteringIterator` and supply @silvanbitterli with a means to plug in the filter he's proposed.

As in

```golang
type CountersFilter func(*types.Counters) bool 

NewFilteringIterator(filter CountersFilter) *Iterator { ... }
```

Sound good?

**Comment by fako1024** [comment] 2023-09-11 08:03
Sure, I can look into that. Just fair warning: Might not be the exact functional approach you're suggesting. Functional arguments cannot be inlined (for obvious reasons) and hence it would be extremely expensive to put a trivial function on the stack each time you want to do a billo if-then-else to decide on the counter increments (for _each_ element).

Most likely the iterator will need an instance of whatever the filter is (a struct / pointer) and _that_ needs to implement a filtering method, but we'll have to see.

All I'm saying: Don't rely on the proposed concept when planning the filter implementation at this point... :wink:

**Comment by basman** [comment] 2023-09-20 13:21
@fako1024 we are happy to receive your iterator "hook" any time soon (at your convenience). In the mean time we are working on the parser to extend the condition syntax and help texts.

**Comment by fako1024** [comment] 2023-09-23 10:25
@basman Sure thing mate, see linked PR for implementation. I think this should cover all of your scenarios (while still being quite generic for potential future extensions), otherwise please let me know.

Once @els0r approves you should be G2G...

**Comment by basman** [comment] 2023-09-23 22:41
Thanks for the PR, that was fast! We will adapt and base our preliminary work on it. While doing so, we will comment on PR#224 to let you know if we got everything we need.

**Comment by els0r** [comment] 2023-09-24 14:28
See approval in PR. Thanks folks 🙌

**Comment by fako1024** [comment] 2023-09-24 14:32
@basman @els0r Since the changes to the hashmap are non-breaking I've already merged that part into main. Feel free to spin up a new branch for the remaining changes...

**Comment by els0r** [comment] 2023-09-24 15:28
Thanks mate! Let's keep the issue open until the remaining changes are done.

**Comment by fako1024** [comment] 2023-09-24 15:43
> Thanks mate! Let's keep the issue open until the remaining changes are done.

Sure thing, didn't intend to close the issue (and didn't have a "Closes" statement in the PR). Github did that all by itself... :rofl:

**Comment by silvanbitterli** [comment] 2023-09-24 16:52
Thanks a lot! I have merged the changes into @basman's and my development fork. 
We will integrate the parsing of the traffic direction filter and create a PR once we have thoroughly tested it.

**Comment by silvanbitterli** [comment] 2023-10-11 17:20
I have merged via the GUI. 
The main branch shows a single commit, but https://github.com/els0r/goProbe/pull/232/commits shows all individual commits. Is this an issue?

**Comment by silvanbitterli** [comment] 2023-10-16 16:02
Thanks a lot for the support! 
The final PR for this issue has been merged.
Shall we close the issue?

**Closed** 2023-10-17 02:37 UTC
Labels: feature
